### ISSUE TITLE
Lazy component improvements

### ISSUE THREAD

**Issue by isc30** [isc30/blazor-lazy-loading#42]
- [x] Ability to specify the module manually when using FullType
- [x] Ability to pass arbitrary Parameters to the wrapped component

**Comment by GioviQ** [comment]
What about adding components from nuget packages?
E.g. MatBlazor

**Comment by isc30** [comment]
That should perfectly fine as long as the Module has a dependency on the nuget packages.

**Comment by isc30** [comment]
Well, actually I do not support referencing PackageReferences as modules, good catch

**Comment by isc30** [comment]
@GioviQ I just opened another ticket to add that functionality, do you want to make a PR yourself or want me to look at it?

**Comment by GioviQ** [comment]
@isc30  I am just new to Blazor and not expert like you. I suggest Nuget packages, because I noticed that they embed wwwroot as static web assets.

**Comment by isc30** [comment]
No worries, I will investigate how to lazy load something like MaterialBlazor and put you as PR reviewer

**Comment by isc30** [comment]
The latest release includes a demo using a component from a nuget package and an explanation on how to generate a manifest for that assembly too :) @GioviQ

**Comment by GioviQ** [comment]
Thanks I will check.

**Comment by GioviQ** [comment]
@isc30  I checked but it is not what I meant. The faso.blazor.spinkit.1.0.1.nupkg package is not download runtime, it is just present in the build unpackaged. So it is just any other components.
Maybe I am not so interested to lazyness but more on modularization like implemented in Orchard.

My ambition is to realize something like https://demo3.tryorchard.net/Admin/Modules/Features but with Blazor.

**Comment by isc30** [comment]
Hmm can you attach a link on how the module system works there?

Also, would #9 solve your needs? If you could execute a Startup when the
module loads.

**Comment by GioviQ** [comment]
My modules implement https://github.com/enkodellc/blazorboilerplate/blob/development/src/Shared/BlazorBoilerplate.Shared/Interfaces/IModule.cs 
so I solved the init. I have to implement donwload and wwwroot folder merge.

**Comment by GioviQ** [comment]
Here the source of Orchard https://github.com/OrchardCMS/Orchard
The core version is still in RC
https://github.com/OrchardCMS/OrchardCore

**Comment by GioviQ** [comment]
I discovered now that https://github.com/oqtane/oqtane.framework has module package download.

**Comment by isc30** [comment]
I think I now understand what you are referring to.

The framework you linked only supports BlazorServer.

If you want to have a fully dynamic runtime module system that can only
work when using some server behind (or some nasty trickery).

This could be implemented easily by using IAssemblyLoader manually and
using this lib as a base.

Having such system is more like a Framework thing. The purpose of this
library is to provide the building blocks to serve and consume assemblies
on demand + some handy components for typical use cases.

Is your expectation to have such modules working on a webassembly
application?

**Comment by GioviQ** [comment]
Oqtane works as Blazor Server or WASM. Now I am watching how it works well.

**Comment by isc30** [comment]
Please keep me posted on this.
If your plan is to "upload" a DLL on runtime (WASM) and loading it, it can be done easily with IAssemblyLoader.
