### ISSUE TITLE
I could not run the demo project properly

### ISSUE THREAD

**Issue by burakakca** [isc30/blazor-lazy-loading#56]
![Screenshot_1](https://user-images.githubusercontent.com/56919004/81953571-813b1f00-9610-11ea-8448-733e2cb4d050.png)

what am i missing ?

**Comment by isc30** [comment]
Hi there, it seems like you are missing the 'LocalNuget.props' file.
You need to build the library first (under /src) to be able to build the demo.

**Comment by isc30** [comment]
If you pull the latest master, you should see a more reasonable error when building the demo before the library.

Let me know if that works

**Comment by burakakca** [comment]
Thanks works fine now.

I have another question, if you want, I can open a new subject.
- No problem with lazy loading work with Blazor PWAs, right?

**Comment by isc30** [comment]
Awesome! I will open a issue to add PWA support to the demo.
Would you like to contribute with that?

**Comment by isc30** [comment]
Thread continued in #58
