### ISSUE TITLE
Can we debug a module with Blazor Wasm?

### ISSUE THREAD

**Issue by fongnx** [isc30/blazor-lazy-loading#63]
I test this case with Visual Studio, the break point was not hit in the module.

**Comment by isc30** [comment]
Hi, no, blazor wasm has many bugs when it comes to debugging. This is
completely out of my hands.

What I usually do is debug everything via dual mode (server) OR add the
ModulesHost to the linker XML so these are downloaded as boot assemblies
and wasm debugging works again.

**Comment by fongnx** [comment]
Thank you!

**Comment by isc30** [comment]
Thanks to you 😄 If you give it a try do you mind confirming if the linker+wasm approach still works? I would like to document it at some point
