### ISSUE TITLE
Only RCL-based components or entire pages?

### ISSUE THREAD

**Issue by MV10** [isc30/blazor-lazy-loading#66]
Hi Ivan, this is an interesting system you've built.

I'm interested in runtime loading of page-based razor component libraries (Blazor server-side), but if I'm reading your readme and wiki correctly, it sounds like this only operates at the component level. Is that accurate?

I suspect page-content RCLs would require somehow registering the newly-loaded page with the router. I saw one of your comments in a closed issue that you were going to ask MS about opening up their router, did you get anywhere with that?

Basically we're planning to build a gigantic (enterprise) system, hundreds of pages, and we're designing around a base "frame" that can host arbitrary content that ideally isn't known at build-time. (We have the beginnings of a page-based system where the "frame" pages are basically two-line stubs -- the `@page` directive and a `<component>` tag that ties to a referenced RCL, it's that need to build One Giant Solution that I'm trying to break.) I was trying to imagine different ways to discover/load that content at runtime -- and unload, so we don't just accumulate assemblies as the user navigates around in the app all day long.

Have you considered anything along these lines? All I've found so far is that Oqtane content management system, but that's too much tie-in for us.

**Comment by isc30** [comment]
Hi there, apart from a component-level resolver, the lib also comes with a `LazyRouter` component that replaces the one from Microsoft and resolves at route level. It seems to be exactly what you need.

https://github.com/isc30/blazor-lazy-loading/wiki/Components-@-LazyRouter

Please note that with the Blazor net5 release, Microsoft took the Router part of the library and now it will be built-in. I will update the lib to use the new Router once that's released. In it's current state, the LazyRouter will solve your needs without much complications. Give it a try and let me know how that goes.

Thanks!

**Comment by MV10** [comment]
They used your router? That's pretty cool. Thanks, I'll take a look at that aspect.
