### ISSUE TITLE
Could not find assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.	

### ISSUE THREAD

**Issue by Daeamon** [isc30/blazor-lazy-loading#68]
Error caused while rebuilding server project.
Screen https://prnt.sc/v6jd2y

**Comment by Daeamon** [comment]
I still can't fix it. The project was completely out of order.

**Comment by isc30** [comment]
Hi, I will need all the versions used in the project/sdks. Does the issue happen when building the Demo from this repo?

**Comment by Daeamon** [comment]
I'm using in all projects net5.0

**Comment by isc30** [comment]
Support for `net5.0 preview` is still in progress. Can be tracked at #65 .
Until this is ready, there isn't much to do.

**Comment by Daeamon** [comment]
((( no i can not build the demo. https://prnt.sc/v7d22z

**Comment by isc30** [comment]
Please try building `/src/BlazorLazyLoading.sln` before the demo solution

**Comment by Daeamon** [comment]
https://prnt.sc/v7dh8r does not work

**Comment by isc30** [comment]
Okay, this seems related to `net5.0` SDK. I will investigate the issue as part of that work
